version: '3.8'

services:
  vzr:
    image: maka7wx/vzr:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    command: gunicorn VZR.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/skk/vzr/static
      - media_volume:/var/vzrFiles
    expose:
      - 7000
    env_file:
      - ./.env.prod

    depends_on:
      - db_vzr
    restart: always
  db_vzr:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/14/main
    env_file:
      - ./.env.prod.db
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/skk/vzr/static
      - media_volume:/var/vzrFiles

    ports:
      - "8080:80"
    depends_on:
      - vzr
    restart: always


  celery:
    build: .
    command: celery -A VZR worker -B -l INFO
    volumes:
      - .:/home/skk/vzr
    env_file:
      - .env.prod
    depends_on:
      - db_vzr
      - redis
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
